---
title: "Youtube Trending analysis"
author: "Ullas Srivastava,Diwei Zhu,Valeriya Gorelova,Wandi Zhang"
date: "12/8/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,cache = T)
```


```{r message=FALSE, warning=FALSE}
library(quanteda)
library(tidyr)
library(tidytext)
library(wordcloud)
library(tm)
library(tidyverse)
library(ggplot2)
```



# PART 1: Exploratory Data Analysis & Text Analytics

```{r}
original_data <- read.csv("USvideos.csv")
```

## 1. How many complaints have been generated?

```{r}
data<-original_data
dim(data)
colnames(data)
if(1){
  temp<-list("category_id","views","likes","dislikes","comment_count","comments_disabled","ratings_disabled","video_error_or_removed")

  for ( i in temp){
  print(paste("========",i,"========="))
  if(is.character(data[[i]])){
 print(table(data[[i]]))
  }else
  {
    print(summary(data[[i]]))
  }
  }
}


```

## data processing

```{r}
#formatting
data$trending_date<-as.Date(data$trending_date, "%y.%d.%m")
data$publish_time<-as.Date(data$publish_time)
data[,"thumbnail_link"]<-NULL
data<-subset(data,!(data$video_id=="kZete48ZtsY"&data$video_error_or_removed=="True"))

#aggregate
data1<-aggregate(data[,c("video_id")],
                 by=list(data$video_id,data$title,data$channel_title,data$category_id,data$publish_time,data$tags,data$comments_disabled,data$ratings_disabled,data$video_error_or_removed,data$description,data$channel_title),
                 FUN = length)
colnames(data1)<-c("video_id","title","channel_title","category_id","publish_time","tags","comments_disabled","ratings_disabled","video_error_or_removed","description","channel_title","count")
data10<-aggregate(data$video_id,by=list(data$video_id),length)
colnames(data10)<-c("video_id","trending_count")

process_list<- list("description","tags","title")
for(i in 1:nrow(data10)){
  ifelse(i%%1000==0,print(paste(i," ",round(i/nrow(data10)*100,2),"%")),0)
  temp<-subset(data,data$video_id==data10[i,"video_id"])
  temp<-temp[order(temp$trending_date,decreasing = T),]
  data10[i,"first_trending"]<-min(temp$trending_date)
  data10[i,"last_trending"]<-max(temp$trending_date)
  
  data10[i,"title"]<-temp[1,"title"]
  data10[i,"title_change_count"]<-length(unique(temp$title))
  
  data10[i,"tags"]<-temp[1,"tags"]
  data10[i,"tag_change_count"]<-length(unique(temp$tags))
  
  data10[i,"description"]<-temp[1,"description"]
  data10[i,"des_change_count"]<-length(unique(temp$description))
  
  data10[i,"category_id"]<-temp[1,"category_id"]
  data10[i,"cat_change_count"]<-length(unique(temp$category_id))
  
  data10[i,"channel_title"]<-temp[1,"channel_title"]
  data10[i,"chn_change_count"]<-length(unique(temp$channel_title))
  
  data10[i,"publish_time"]<-min(temp$publish_time)
  
  data10[i,"views"]<-temp[1,"views"]
  data10[i,"max_view"]<-max(temp$views)
  data10[i,"min_view"]<-min(temp$views)
  
  data10[i,"likes"]<-temp[1,"likes"]
  data10[i,"max_likes"]<-max(temp$likes)
  data10[i,"min_likes"]<-min(temp$likes)
  
  data10[i,"dislikes"]<-temp[1,"dislikes"]
  data10[i,"max_dislikes"]<-max(temp$dislikes)
  data10[i,"min_dislikes"]<-min(temp$dislikes)
  
  data10[i,"comment_count"]<-temp[1,"comment_count"]
  data10[i,"max_comments"]<-max(temp$comment_count)
  data10[i,"min_comments"]<-min(temp$comment_count)
  
  data10[i,"comments_disabled"]<-temp[1,"comments_disabled"]
  data10[i,"ratings_disabled"]<-temp[1,"ratings_disabled"]
  data10[i,"video_error_or_removed"]<-temp[1,"video_error_or_removed"]
  
  
}

data10$description<-str_replace_all(data10$description,"http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+","EXTERNALURL ")
data10$description<-str_replace_all(data10$description,"(\\\\r\\n|\\\\r|\\\\n)"," ")
data10$des_url_count<-unlist(lapply(data10$description,function(x){length(str_extract_all(x,"EXTERNALURL")[[1]])}))
data10$description<-str_replace_all(data10$description,"EXTERNALURL"," ")
for (j in process_list){
    data10[[paste(j,"P")]] <- gsub("'", "", data10[[j]]) # remove apostrophes
    data10[[paste(j,"P")]] <- gsub("[[:punct:]]", " ", data10[[j]])  # replace punctuation with space
    data10[[paste(j,"P")]] <- gsub("[[:cntrl:]]", " ", data10[[j]])  # replace control characters with space
    data10[[paste(j,"P")]] <- gsub("^[[:space:]]+", "", data10[[j]]) # remove whitespace at beginning of documents
    data10[[paste(j,"P")]] <- gsub("[[:space:]]+$", "", data10[[j]]) # remove whitespace at end of documents
    data10[[paste(j,"P")]] <- gsub("[^a-zA-Z -]", " ", data10[[j]]) # allows only letters
    data10[[paste(j,"P")]] <- tolower(data10[[j]]) 
  }
data10$trending_span = as.numeric(data10$last_trending-data10$first_trending)
data10$day_until_trending = as.numeric(data10$first_trending-data10$publish_time)
data10$like_rate=round(data10$likes/(data10$likes+data10$dislikes)*100,2)
data10$like_engage_rate=round((data10$likes+data10$dislikes)/data10$views*100,2)
data10$comment_engage_rate=round(data10$comment_count/data10$views*100,2)
data10$view_increment=ifelse(data10$trending_span>0,round((data10$max_view-data10$min_view)/data10$trending_span,2),0)
data10$like_increment=ifelse(data10$trending_span>0,round((data10$max_likes-data10$min_likes)/data10$trending_span,2),0)
data10$dislike_increment=ifelse(data10$trending_span>0,round((data10$max_dislikes-data10$min_dislikes)/data10$trending_span,2),0)
data10$comment_increment=ifelse(data10$trending_span>0,round((data10$max_comments-data10$min_comments)/data10$trending_span,2),0)
data10$engagement_score<-50*data10$comment_count/25000 +20*(data10$likes+data10$dislikes)/500000-5*data10$day_until_trending+10*data10$view_increment/250 +5*data10$views/50000000

cat_dict<-c("Film & Animation","Autos & Vehicles","Music","Pets & Animals","Sports","Short Movies","Travel & Events","Gaming","Videoblogging","People & Blogs","Comedy","Entertainment","News & Politics","Howto & Style","Education","Science & Technology","Nonprofits & Activism","Movies","Anime/Animation","Action/Adventure","Classics","Comedy","Documentary","Drama","Family","Foreign","Horror","Sci-Fi/Fantasy","Thriller","Shorts","Shows","Trailers")
names(cat_dict)<-c(1,2,10,15,17:44)

data10$category_name<-unlist(lapply(data10$category_id,function(x){
  return(cat_dict[[toString(x)]])
}))
```



```{r}
colnames(data10)
```




```{r date distribute} 
temp <- data10$first_trending
temp<-data.frame(temp)
temp$pub <-data10$publish_time
temp$diff<-data10$day_until_trending
temp$PUByearmonth<-format(temp$pub,"%Y-%m")
temp$TRDyearmonth<-format(temp$temp,"%Y-%m")

ggplot(data = temp[temp$PUByearmonth<"2017-10",],mapping = aes(x=PUByearmonth))+geom_bar()+theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("first publish date (before 2017-10)")
ggplot(data = temp[temp$PUByearmonth>="2017-10",],mapping = aes(x=PUByearmonth))+geom_bar()+ theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("first publish date (after 2017-10)(included)")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = temp,mapping = aes(x=TRDyearmonth))+geom_bar()+ theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("first trending date")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,mapping = aes(x=trending_count))+geom_bar()+
  ggtitle("how many times on trending")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,mapping = aes(x=trending_span))+geom_bar()+
  ggtitle("how many days between first and last trending")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
```




```{r word cloud}

newscorpus_des<- corpus(data10$`description P`,
                    docnames=data10$video_id,
                    docvar=data.frame(pos=data10$publish_time,
                                      date=data10$first_trending,
                                      loc = data10$views))

newscorpus_tag<- corpus(data10$`tags P`,
                    docnames=data10$video_id,
                    docvar=data.frame(pos=data10$publish_time,
                                      date=data10$first_trending,
                                      loc = data10$views))

newscorpus_title<- corpus(data10$`title P`,
                    docnames=data10$video_id,
                    docvar=data.frame(pos=data10$publish_time,
                                      date=data10$first_trending,
                                      loc = data10$views))



```



```{r}
newscorpus<-newscorpus_des

dfm.simple<- dfm(newscorpus, 
               remove = c(stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.simple, n=50)

swlist = c(",", ":",".", "â", "€","-","!","™","¢",")","(","/","_","\"","s","º","\'","|","&","»","ë","ì","t","can","˜","¸","+","ð","ðÿ","¶","¡","linebreak","„","âž","°")
dfm.stem<- dfm(newscorpus, 
               remove = c(swlist,stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.stem, n=50)


set.seed(333)   #keeps cloud' shape fixed
freq<-topfeatures(dfm.stem, n=500)

wordcloud(names(freq), 
          freq, max.words=100, 
          scale=c(3, .3), 
          colors=brewer.pal(8, "Dark2"))
```


```{r}
newscorpus<-newscorpus_tag

dfm.simple<- dfm(newscorpus, 
               remove = c(stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.simple, n=50)

swlist = c("‚", ":",".", "à", "€","-","!","¤","¢",")","(","/","_","\"","s","?","º","\'","|","&","»","ë","ì","t","can","˜","¸","+","¥","=","¶","¡","linebreak","„","âž","°")
dfm.stem<- dfm(newscorpus, 
               remove = c(swlist,stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.stem, n=50)


set.seed(142)   #keeps cloud' shape fixed
freq<-topfeatures(dfm.stem, n=500)

wordcloud(names(freq), 
          freq, max.words=120, 
          scale=c(3, .3), 
          colors=brewer.pal(8, "Dark2"))
```


```{r}
newscorpus<-newscorpus_title

dfm.simple<- dfm(newscorpus, 
               remove = c(stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.simple, n=50)

swlist = c(",", ":",".", "à", "€","-","!","¤","¢",")","(","/","_","\"","ë","?","º","\'","|","&","[","]","ì","ðÿ","™","˜","¸","+","¥","=","¶","¡","â","„","©","$")
dfm.stem<- dfm(newscorpus, 
               remove = c(swlist,stopwords("english")), 
               verbose=F, 
               stem=F)
topfeatures(dfm.stem, n=50)


set.seed(142)   #keeps cloud' shape fixed
freq<-topfeatures(dfm.stem, n=500)

wordcloud(names(freq), 
          freq, max.words=200, 
          scale=c(3, .3), 
          colors=brewer.pal(8, "Dark2"))
```

```{r cat distribute&top tags}

ggplot(data = data10,aes(category_name))+geom_bar()+ theme(axis.text.x = element_text(angle = 90, hjust = 1))+ggtitle("category distribution")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
swlist = c("‚", ":",".", "à", "€","-","!","¤","¢",")","(","/","_","\"","s","º","\'","|","&","»","ë","ì","t","can","˜","¸","+","¥","=","¶","¡","linebreak","„","âž","°","ð","ñ")
data30<-data.frame(cat_dict)
for(i in 1:nrow(data30)){
#i=2
  #ifelse(i%%100==0,print(paste(i," ",round(i/nrow(data20)*100,2),"%")),0)
  
  temp<-subset(data10,data10$category_name==data30[i,1])
  if(nrow(temp)==0){
    next
  }
  newscorpus_temp<- corpus(temp$`tags P`,docnames=temp$video_id)
  dfm.stem<- dfm(newscorpus_temp, 
               remove = c(swlist,stopwords("english")), 
               verbose=F,stem=F)
  temp_list<-topfeatures(dfm.stem, n=5)
  data30[i,"top_tag"]<-ifelse(temp_list[1]>=1,names(temp_list[1]),NA)
  data30[i,"second_tag"]<-ifelse(length(temp_list>1)&temp_list[2]>=1,names(temp_list[2]),NA)
  data30[i,"third_tag"]<-ifelse(length(temp_list>2)&temp_list[3]>=1,names(temp_list[3]),NA)
  data30[i,"fourth_tag"]<-ifelse(length(temp_list>3)&temp_list[4]>=1,names(temp_list[4]),NA)
}
data30[!is.na(data30$top_tag),]
```


```{r number hist}
#continuos use histogram
#cat without y use bar
#cat with y use col
ggplot(data = data10,aes(trending_count))+geom_bar()+
  ggtitle("How many days a video is trending")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(title_change_count))+geom_bar()+
  ggtitle("times a video changed titles")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(tag_change_count))+geom_bar()+
  ggtitle("times a video changed tags")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(des_change_count))+geom_bar()+
  ggtitle("times a video changed description")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(cat_change_count))+geom_bar()+
  ggtitle("times a video changed category")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(chn_change_count))+geom_bar()+
  ggtitle("times a video's owner change vhannel title")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(views))+geom_histogram(bins=15)+
  ggtitle("views distribution")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$views<=15000000,],aes(views))+geom_histogram(bins=15)+
  ggtitle("views distribution <=15000000")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$views>15000000,],aes(views))+geom_histogram(bins=15)+
  ggtitle("views distribution >15000000")+xlim(15000000,max(data10$views))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$likes<=100000,],aes(likes))+geom_histogram(bins=15)+
  ggtitle("likes distribution <=100000")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$likes>100000,],aes(likes))+geom_histogram(bins=15)+
  ggtitle("likes distribution >100000")+xlim(100000,max(data10$likes))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$dislikes<=100000,],aes(dislikes))+geom_histogram(bins=15)+
  ggtitle("dislikes distribution <=100000")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$dislikes>100000,],aes(dislikes))+geom_histogram(bins=15)+
  ggtitle("dislikes distribution >100000")+xlim(100000,max(data10$dislikes))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$comment_count<=100000,],aes(comment_count))+geom_histogram(bins=15)+
  ggtitle("comment_count distribution <=100000")+
 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$comment_count>100000,],aes(comment_count))+geom_histogram(bins=15)+
  ggtitle("comment_count distribution >100000")+xlim(100000,max(data10$comment_count))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(comments_disabled))+geom_bar()+
  ggtitle("is the video disabled comments")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(ratings_disabled))+geom_bar()+
  ggtitle("is the video disabled ratings")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(video_error_or_removed))+geom_bar()+ 
  ggtitle("is the video disabled removed")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(des_url_count))+geom_histogram()+
  ggtitle("how many external links in the description")+
  stat_bin( geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(trending_span))+geom_histogram()+
  ggtitle("how many days between first and last day trending")+
  stat_bin( geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(log2(day_until_trending)))+geom_histogram()+
  ggtitle("how many days until trending log2")+
  stat_bin( geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$day_until_trending<=100,],aes(day_until_trending))+geom_histogram(bins=15)+
  ggtitle("how many days until trending <=100")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$day_until_trending>100,],aes(day_until_trending))+geom_histogram(bins=15)+
  ggtitle("how many days until trending >100")+ 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)

ggplot(data = data10,aes(like_rate))+geom_histogram()+
  
  ggtitle("video like rate distribution")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(like_engage_rate))+geom_histogram()+
  ggtitle("percentage of like interaction distribution")+ 
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10,aes(comment_engage_rate))+geom_histogram()+
  ggtitle("percentage of comments interaction distribution")+
  stat_count(geom = "text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)

ggplot(data = data10[data10$view_increment<=1000000,],aes(view_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(<=1000000)")+ 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$view_increment>1000000,],aes(view_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(>1000000)")+xlim(1000000,max(data10$view_increment))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)

ggplot(data = data10[data10$like_increment<=3000,],aes(like_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(<=3000)")+ 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$like_increment>3000,],aes(like_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(>3000)")+xlim(3000,max(data10$like_increment))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)

ggplot(data = data10[data10$dislike_increment<=1000,],aes(dislike_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(<=1000)")+ 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$dislike_increment>1000,],aes(dislike_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(>1000)")+xlim(1000,max(data10$dislike_increment))+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)

ggplot(data = data10[data10$comment_increment<=1000,],aes(comment_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(<=1000)")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)
ggplot(data = data10[data10$comment_increment>1000,],aes(comment_increment))+geom_histogram(bins=15)+
  ggtitle("average view increment when trending(>1000)")+xlim(1000,max(data10$comment_increment))+ 
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)


ggplot(data = data10,aes(engagement_score))+geom_histogram(bins=15)+
  ggtitle("engagement score distribution")+
  stat_bin(bins=15, geom="text", colour = "black", size = 3.5,aes(label = ..count..),vjust=-0.3)



```



```{r youtuber}
#youtuberAG_list<-c("channel_title","min_view","min_likes","min_dislikes","min_comments")
temp_avg<-c("trending_count","title_change_count","tag_change_count","des_change_count","cat_change_count","views","likes","dislikes","comment_count","des_url_count","trending_span","day_until_trending","like_rate","like_engage_rate","comment_engage_rate","engagement_score","view_increment","like_increment","dislike_increment","comment_increment")
temp_max<-c("max_view","max_likes","max_dislikes","max_comments","trending_span","engagement_score","view_increment","like_increment","dislike_increment","comment_increment")
temp_sum<-c("views","comment_count","likes")
temp_top<-c("tags","category_name")

data20<- aggregate(data10$video_id,by=list(data10$channel_title),FUN=length)
colnames(data20)<-c("channel","trend_video_count") 
swlist = c("‚", ":",".", "à", "€","-","!","¤","¢",")","(","/","_","\"","s","º","\'","|","&","»","ë","ì","t","ìš","˜","¸","+","¥","=","¶","¡","¬","„","ãƒ","°","ã",
"[","ð","´")
for(i in 1:nrow(data20)){
#i=2
  ifelse(i%%100==0,print(paste(i," ",round(i/nrow(data20)*100,2),"%")),0)
  
  temp<-subset(data10,data10$channel_title==data20[i,"channel"])
  #temp<-temp[order(temp$trending_date,decreasing = T),]
  for(j in temp_avg){
    data20[i,paste("avg_",j,sep = "")]<-mean(temp[[j]])
  }
  
  for(j in temp_max){
    data20[i,paste("max_",j,sep = "")]<-max(temp[[j]])
  }
  for(j in temp_sum){
    data20[i,paste("sum_",j,sep = "")]<-sum(temp[[j]])
  }
  
  newscorpus_temp<- corpus(temp$`tags P`,docnames=temp$video_id)
  dfm.stem<- dfm(newscorpus_temp, 
               remove = c(swlist,stopwords("english")), 
               verbose=F,stem=F)
  
  temp_list<-topfeatures(dfm.stem, n=2)
  data20[i,"top_tag"]<-ifelse(temp_list[1]>=1,names(temp_list[1]),NA)
  data20[i,"second_tag"]<-ifelse(length(temp_list>1)&temp_list[2]>=1,names(temp_list[2]),NA)
  temp_list<-table(temp$category_name)
  data20[i,"top_cat"]<-names(temp_list[1])
  data20[i,"second_cat"]<-ifelse(length(temp_list>1),names(temp_list[2]),NA)
}

#only 101 have trending in more than 1 cat

```

```{r}
colnames(data20)
```


```{r youtuber plot ,fig.width=8.5,fig.height=4}
temp<-data20[order(-data20$trend_video_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,trend_video_count),y=trend_video_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many times its video is trending")+
  geom_text(aes(label=round(trend_video_count,0),hjust=ifelse(trend_video_count<max(temp$trend_video_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$trend_video_count,function(x){return(ifelse(x<max(temp[1:25,]$trend_video_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_trending_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_trending_count),y=avg_trending_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many days its trending video will stay trending(average)")+
  geom_text(aes(label=round(avg_trending_count,0),hjust=ifelse(avg_trending_count<max(temp$avg_trending_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_trending_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_trending_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_title_change_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_title_change_count),y=avg_title_change_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many times the it changed it's trending video title")+
  geom_text(aes(label=round(avg_title_change_count,0),hjust=ifelse(avg_title_change_count<max(temp$avg_title_change_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_title_change_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_title_change_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_tag_change_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_tag_change_count),y=avg_tag_change_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many times the it changed it's trending video tag")+
  geom_text(aes(label=round(avg_tag_change_count,2),hjust=ifelse(avg_tag_change_count<max(temp$avg_tag_change_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_tag_change_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_tag_change_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_des_change_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_des_change_count),y=avg_des_change_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many times the it changed it's trending video description")+
  geom_text(aes(label=round(avg_des_change_count,2),hjust=ifelse(avg_des_change_count<max(temp$avg_des_change_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_des_change_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_des_change_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_cat_change_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_trending_count),y=avg_cat_change_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many times the it changed it's trending video category")+
  geom_text(aes(label=round(avg_cat_change_count,2),hjust=ifelse(avg_cat_change_count<max(temp$avg_cat_change_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_cat_change_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_cat_change_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_views,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_views),y=avg_views))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many view will its trending video get")+
  geom_text(aes(label=round(avg_views,0),hjust=ifelse(avg_views<max(temp$avg_views)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_views,function(x){return(ifelse(x<max(temp[1:25,]$avg_views)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_likes,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_views),y=avg_views))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many likes will its trending video get")+
  geom_text(aes(label=round(avg_views,0),hjust=ifelse(avg_views<max(temp$avg_views)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_views,function(x){return(ifelse(x<max(temp[1:25,]$avg_views)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_dislikes,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_views),y=avg_views))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many dislikes will its trending video get")+
  geom_text(aes(label=round(avg_views,0),hjust=ifelse(avg_views<max(temp$avg_views)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_views,function(x){return(ifelse(x<max(temp[1:25,]$avg_views)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_comment_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_comment_count),y=avg_comment_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many comments will its trending video get")+
  geom_text(aes(label=round(avg_comment_count,0),hjust=ifelse(avg_comment_count<max(temp$avg_comment_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_comment_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_comment_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_des_url_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_des_url_count),y=avg_des_url_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many URL will its trending video have in the description")+
  geom_text(aes(label=round(avg_des_url_count,0),hjust=ifelse(avg_des_url_count<max(temp$avg_des_url_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_des_url_count,function(x){return(ifelse(x<max(temp[1:25,]$avg_des_url_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_trending_span,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_trending_span),y=avg_trending_span))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many days will its trending video can last")+
  geom_text(aes(label=round(avg_trending_span,0),hjust=ifelse(avg_trending_span<max(temp$avg_trending_span)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_trending_span,function(x){return(ifelse(x<max(temp[1:25,]$avg_trending_span)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_day_until_trending,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_day_until_trending),y=avg_day_until_trending))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many days will its trending video need to become trending(average)")+
  geom_text(aes(label=round(avg_day_until_trending,0),hjust=ifelse(avg_day_until_trending<max(temp$avg_day_until_trending)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_day_until_trending,function(x){return(ifelse(x<max(temp[1:25,]$avg_day_until_trending)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_like_rate,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_like_rate),y=avg_like_rate))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many viewers likes its trending video (average)")+
  geom_text(aes(label=round(avg_like_rate,0),hjust=ifelse(avg_like_rate<max(temp$avg_like_rate)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_like_rate,function(x){return(ifelse(x<max(temp[1:25,]$avg_like_rate)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_like_engage_rate,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_like_engage_rate),y=avg_like_engage_rate))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many viewer will click its trending video's like / dislike")+
  geom_text(aes(label=round(avg_like_engage_rate,2),hjust=ifelse(avg_like_engage_rate<max(temp$avg_like_engage_rate)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_like_engage_rate,function(x){return(ifelse(x<max(temp[1:25,]$avg_like_engage_rate)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_comment_engage_rate,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_comment_engage_rate),y=avg_comment_engage_rate))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("How many viewer will leave comments on its trending video")+
  geom_text(aes(label=round(avg_comment_engage_rate,2),hjust=ifelse(avg_comment_engage_rate<max(temp$avg_comment_engage_rate)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_comment_engage_rate,function(x){return(ifelse(x<max(temp[1:25,]$avg_comment_engage_rate)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_max_view,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_max_view),y=max_max_view))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("channnel")+
  geom_text(aes(label=round(max_max_view,0),hjust=ifelse(max_max_view<max(temp$max_max_view)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_max_view,function(x){return(ifelse(x<max(temp[1:25,]$max_max_view)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_max_likes,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_max_likes),y=max_max_likes))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many likes this youtuber ever have on single trending video")+
  geom_text(aes(label=round(max_max_likes,0),hjust=ifelse(max_max_likes<max(temp$max_max_likes)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_max_likes,function(x){return(ifelse(x<max(temp[1:25,]$max_max_likes)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_max_dislikes,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_max_dislikes),y=max_max_dislikes))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many dislikes this youtuber ever have on single trending video")+
  geom_text(aes(label=round(max_max_dislikes,0),hjust=ifelse(max_max_dislikes<max(temp$max_max_dislikes)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_max_dislikes,function(x){return(ifelse(x<max(temp[1:25,]$max_max_dislikes)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_max_comments,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_max_comments),y=max_max_comments))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many comments this youtuber ever have on single trending video")+
  geom_text(aes(label=round(max_max_comments,0),hjust=ifelse(max_max_comments<max(temp$max_max_comments)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_max_comments,function(x){return(ifelse(x<max(temp[1:25,]$max_max_comments)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_trending_span,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_trending_span),y=max_trending_span))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many days its long lasting video stay trending")+
  geom_text(aes(label=round(max_trending_span,0),hjust=ifelse(max_trending_span<max(temp$max_trending_span)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_trending_span,function(x){return(ifelse(x<max(temp[1:25,]$max_trending_span)/1.5, "black","white"))})))

temp<-data20[order(-data20$sum_views,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,sum_views),y=sum_views))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many view this youtuber have for all its trending video")+
  geom_text(aes(label=round(sum_views,0),hjust=ifelse(sum_views<max(temp$sum_views)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$sum_views,function(x){return(ifelse(x<max(temp[1:25,]$sum_views)/1.5, "black","white"))})))

temp<-data20[order(-data20$sum_comment_count,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,sum_comment_count),y=sum_comment_count))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many comments this youtuber have for all its trending video")+
  geom_text(aes(label=round(sum_comment_count,0),hjust=ifelse(sum_comment_count<max(temp$sum_comment_count)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$sum_comment_count,function(x){return(ifelse(x<max(temp[1:25,]$sum_comment_count)/1.5, "black","white"))})))

temp<-data20[order(-data20$sum_likes,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,sum_likes),y=sum_likes))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("how many likes this youtuber have for all its trending video")+
  geom_text(aes(label=round(sum_likes,0),hjust=ifelse(sum_likes<max(temp$sum_likes)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$sum_likes,function(x){return(ifelse(x<max(temp[1:25,]$sum_likes)/1.5, "black","white"))})))

temp<-aggregate(data20$top_tag,by=list(data20$top_tag),FUN=length)
temp<-temp[order(-temp$x,decreasing = F),]
ggplot(data = temp[1:30,],mapping = aes(x=reorder(Group.1,-x),y=x))+geom_col()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("most common tags among youtubers")+
  geom_text(geom = "text", colour = "black", size = 3.5,aes(label = x),vjust=-0.3)

temp<-aggregate(data20$top_cat,by=list(data20$top_cat),FUN=length)
temp<-temp[order(-temp$x,decreasing = F),]
ggplot(data = temp[1:16,],mapping = aes(x=reorder(Group.1,-x),y=x))+geom_col()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("most common category among youtubers")+
  geom_text(geom = "text", colour = "black", size = 3.5,aes(label = x),vjust=-0.3)

temp<-data20[order(-data20$avg_engagement_score,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_engagement_score),y=avg_engagement_score))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest average engagement score")+
  geom_text(aes(label=round(avg_engagement_score,0),hjust=ifelse(avg_engagement_score<max(temp$avg_engagement_score)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_engagement_score,function(x){return(ifelse(x<max(temp[1:25,]$avg_engagement_score)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_engagement_score,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_engagement_score),y=max_engagement_score))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest singel video engagement score")+
  geom_text(aes(label=round(max_engagement_score,0),hjust=ifelse(max_engagement_score<max(temp$max_engagement_score)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_engagement_score,function(x){return(ifelse(x<max(temp[1:25,]$max_engagement_score)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_view_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_view_increment),y=avg_view_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest average view increment when trending")+
  geom_text(aes(label=round(avg_view_increment,0),hjust=ifelse(avg_view_increment<max(temp$avg_view_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_view_increment,function(x){return(ifelse(x<max(temp[1:25,]$avg_view_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_view_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_view_increment),y=max_view_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest singel video view increment")+
  geom_text(aes(label=round(max_view_increment,0),hjust=ifelse(max_view_increment<max(temp$max_view_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_view_increment,function(x){return(ifelse(x<max(temp[1:25,]$max_view_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_like_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_like_increment),y=avg_like_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest average like increment when trending")+
  geom_text(aes(label=round(avg_like_increment,0),hjust=ifelse(avg_like_increment<max(temp$avg_like_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_like_increment,function(x){return(ifelse(x<max(temp[1:25,]$avg_like_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_like_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_like_increment),y=max_like_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest singel video like increment")+
  geom_text(aes(label=round(max_like_increment,0),hjust=ifelse(max_like_increment<max(temp$max_like_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_like_increment,function(x){return(ifelse(x<max(temp[1:25,]$max_like_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_dislike_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_dislike_increment),y=avg_dislike_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest average dislike increment when trending")+
  geom_text(aes(label=round(avg_dislike_increment,0),hjust=ifelse(avg_dislike_increment<max(temp$avg_dislike_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_dislike_increment,function(x){return(ifelse(x<max(temp[1:25,]$avg_dislike_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_dislike_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_dislike_increment),y=max_dislike_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest singel video dislike increment")+
  geom_text(aes(label=round(max_dislike_increment,0),hjust=ifelse(max_dislike_increment<max(temp$max_dislike_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_dislike_increment,function(x){return(ifelse(x<max(temp[1:25,]$max_dislike_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$avg_comment_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,avg_comment_increment),y=avg_comment_increment))+geom_col()+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  ggtitle("top youtubers with highest average comment increment when trending")+
  geom_text(aes(label=round(avg_comment_increment,0),hjust=ifelse(avg_comment_increment<max(temp$avg_comment_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$avg_comment_increment,function(x){return(ifelse(x<max(temp[1:25,]$avg_comment_increment)/1.5, "black","white"))})))

temp<-data20[order(-data20$max_comment_increment,decreasing = F),]
ggplot(data = temp[1:25,],mapping = aes(x=reorder(channel,max_comment_increment),y=max_comment_increment))+geom_col()+
  ggtitle("top youtubers with highest singel video comment increment")+coord_flip()+xlab(element_blank())+ylab(element_blank())+
  geom_text(aes(label=round(max_comment_increment,0),hjust=ifelse(max_comment_increment<max(temp$max_comment_increment)/1.5, -0.1, 1.1)),size=3,color=unlist(lapply(temp[1:25,]$max_comment_increment,function(x){return(ifelse(x<max(temp[1:25,]$max_comment_increment)/1.5, "black","white"))})))
```











